### ISSUE TITLE
Hi, i just translate css-doodle document site to Chinese version

### ISSUE THREAD

**Issue by keelii** [css-doodle/css-doodle.github.io#4]
Hi there ~ recently, I found css-doodle, which totally amazing and blow-up my mind. then i translate css-doodle document site to Chinese version and publish to a Chinese site [http://css-doodle.cn/](http://css-doodle.cn/), i just wondering could you add a link to this site, maybe Chinese developer will fill in love with css-doodle ❤️

**Comment by yuanchuan** [comment]
非常感谢!

我一直没有考虑中文文档有几个原因：

1. 原始文档一有更改，就需要改中文。当前代码结构并不支持这种多语言的维护。重新调整或在现有代码结构上去维护都需要花很多精力。

2.  css-doodle 目前仍然在实验阶段，将来需要调整的地方可能会比较大，包括官网整体改版。

css-doodle.cn 创建后，会增加维护时间。

3. 域名的费用(一分也是钱)，加管理维护
4. 单独在另外的一个 repo，需要手动比较同步。很可能不会及时更新

所以我想再多考虑下，等 1.0 发布后再说。并且我现在的兴趣也在其他地方。

总之，非常感谢!

**Comment by keelii** [comment]
好的，后续如果有新版发布/翻译计划可以联系我。

**Comment by yuanchuan** [comment]
OK
